name: staging

on:
 push:
  branches:  [develop]

jobs:
  write-to-console:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Staging
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command: |
            cd /var/www/html/bs_frontend && pwd && whoami && export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && git pull origin develop && npm install && npm run build
    
